"""demo flow 脚本的构造和本地运行测试。"""

from __future__ import annotations

from io import BytesIO

from pptx import Presentation

from persistence import InMemoryArtifactStore
from scripts.run_demo_flow import (
    DemoFlowSettings,
    build_demo_runner,
    parse_args,
    run_demo_flow,
    settings_from_args,
)


def test_demo_flow_settings_parse_defaults(tmp_path) -> None:
    """CLI 参数应默认使用 memory/rule demo 路径。"""

    args = parse_args(["--db-path", str(tmp_path / "demo.sqlite"), "--skip-sse"])
    settings = settings_from_args(args)

    assert settings.db_path == tmp_path / "demo.sqlite"
    assert settings.session_id == "demo-session"
    assert settings.direct_question == "Show monthly GMV trend"
    assert settings.exploration_question == "Explore ecommerce performance"
    assert settings.include_sse is False
    assert settings.llm_nodes == []


def test_demo_runner_uses_memory_backend_and_demo_datasource(tmp_path) -> None:
    """demo runner 构造不应连接外部服务或真实 LLM。"""

    settings = DemoFlowSettings(db_path=tmp_path / "demo.sqlite")
    runner = build_demo_runner(settings)

    assert runner.data_source is not None
    assert runner.data_source.datasource_id == "ecommerce-demo-sqlite"
    assert runner.llm_client is None


def test_demo_flow_runs_standard_steps_without_external_services(tmp_path) -> None:
    """demo flow 应跑通 profile、analysis、exploration 和三个 confirm export。"""

    settings = DemoFlowSettings(db_path=tmp_path / "demo.sqlite")
    summary = run_demo_flow(settings)
    commands = [step["command"] for step in summary["steps"]]
    statuses = [step["status"] for step in summary["steps"]]

    assert commands == [
        "profile",
        "analyze",
        "explore",
        "report",
        "excel_confirm",
        "ppt_confirm",
        "dashboard_confirm",
    ]
    assert statuses[:3] == ["completed", "completed", "completed"]
    assert statuses[3] == "waiting_for_human"
    assert statuses[4:] == ["completed", "completed", "completed"]
    assert len(summary["artifact_refs"]) >= 4
    assert len(summary["artifact_refs"]) == len(set(summary["artifact_refs"]))
    assert all(ref.startswith("artifact:") for ref in summary["artifact_refs"])
    assert all(
        step["events"].count("done") <= 1
        for step in summary["steps"]
        if step["status"] == "completed"
    )
    assert any(step["sse_event_count"] > 0 for step in summary["steps"])
    assert "orders" in summary["db"]["tables"]


def test_demo_flow_ppt_confirm_generates_readable_pptx_artifact(tmp_path) -> None:
    """demo flow ppt_confirm should generate a readable PPTX artifact."""

    artifact_store = InMemoryArtifactStore()
    summary = run_demo_flow(
        DemoFlowSettings(db_path=tmp_path / "demo.sqlite"),
        artifact_store=artifact_store,
    )
    ppt_step = next(step for step in summary["steps"] if step["command"] == "ppt_confirm")

    assert ppt_step["status"] == "completed"
    assert ppt_step["error_message"] is None
    assert ppt_step["errors"] == []

    ppt_record = _ppt_artifact_record(artifact_store, ppt_step["artifact_refs"])
    presentation = Presentation(BytesIO(ppt_record.content))
    slide_text = "\n".join(
        shape.text
        for slide in presentation.slides
        for shape in slide.shapes
        if hasattr(shape, "text") and shape.text
    )

    assert len(presentation.slides) == 5
    assert "Analysis deck: Show monthly GMV trend" in slide_text
    assert "Chart Artifact Reference" in slide_text


def _ppt_artifact_record(artifact_store: InMemoryArtifactStore, artifact_refs: list[str]):
    """Return the PPTX artifact record referenced by demo flow output."""

    for artifact_ref in artifact_refs:
        record = artifact_store.get_artifact(artifact_ref)
        if record is not None and record.metadata.get("report_type") == "pptx":
            return record
    raise AssertionError("No pptx artifact was generated by demo flow.")
