"""SQL drafting, validation, and safety metadata schemas."""

from __future__ import annotations

from enum import StrEnum

from pydantic import Field

from schemas._base import StrictBaseModel


class SqlDialect(StrEnum):
    """SQL dialect labels used before execution tools are selected."""

    UNKNOWN = "unknown"
    SQLITE = "sqlite"
    POSTGRES = "postgres"
    MYSQL = "mysql"
    DUCKDB = "duckdb"


class SqlValidationStatus(StrEnum):
    """Validation status before a query is allowed to execute."""

    PENDING = "pending"
    VALID = "valid"
    INVALID = "invalid"
    RISKY = "risky"


class SqlDraft(StrictBaseModel):
    """Draft SQL and narrow metadata generated by the SQL drafter node."""

    query: str
    dialect: SqlDialect = SqlDialect.UNKNOWN
    rationale: str | None = None
    referenced_tables: list[str] = Field(default_factory=list)
    referenced_columns: list[str] = Field(default_factory=list)
    used_tables: list[str] = Field(default_factory=list)
    used_fields: list[str] = Field(default_factory=list)
    generation_strategy: str = "unknown"


class SqlValidation(StrictBaseModel):
    """Result of validating SQL against guards and the database profile."""

    status: SqlValidationStatus = SqlValidationStatus.PENDING
    is_valid: bool = False
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    estimated_rows: int | None = Field(default=None, ge=0)
    estimated_seconds: float | None = Field(default=None, ge=0)
